version: '3.8'

services:
  draftengine:
    image: mattjordan/watermelon-cup:latest
    ports:
      - "8080:8080"
    environment:
      # Option 1: Use a mounted file path (default)
      - FIREBASE_CREDENTIALS_PATH=/app/credentials/firebase-credentials.json
      - SPRING_PROFILES_ACTIVE=prod
      - SHEETS_SPREADSHEET_ID=${SHEETS_SPREADSHEET_ID:-}
    volumes:
      # Mount local credentials directory
      - ${CREDENTIALS_DIR:-./credentials}:/app/credentials
